[package]
name = "ksignal"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "ksignal management library for X-Kernel"
keywords = ["ksignal", "ipc"]
license.workspace = true
repository.workspace = true

[dependencies]
kaddr_layout.workspace = true
kcpu.workspace = true
kerrno.workspace = true
khal.workspace = true
ktime_types.workspace = true
kiface.workspace = true
bitflags = { workspace = true }
cfg-if = { workspace = true }
derive_more = { version = "2.0", default-features = false, features = ["full"] }
kspin = { workspace = true }
kpoll.workspace = true
linux-raw-sys = { workspace = true, default-features = false, features = [
    "general",
    "no_std",
] }
log = { workspace = true }
memaddr.workspace = true
memspace.workspace = true
osvm = {workspace = true}
posix-types.workspace = true
strum = { workspace = true }
unittest.workspace = true
