[package]
name = "rtc-driver"
description = "external RTC drivers for x-kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
default = []
goldfish = ["dep:riscv_goldfish"]
pl031 = ["dep:arm_pl031"]
cmos = ["dep:x86_rtc"]
ls7a = ["dep:chrono"]

[dependencies]
khal = { workspace = true }
ktime_types = { workspace = true }
of = { workspace = true }
memspace = { workspace = true }
log = { workspace = true }
riscv_goldfish = { version = "0.1", optional = true }
arm_pl031 = { version = "0.2", optional = true }
x86_rtc = { version = "0.1", optional = true }
chrono = { workspace = true, optional = true }
unittest.workspace = true
