[package]
name = "kuaccess"
description = "Kernel user-memory access glue for X-Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.cargo-shear]
ignored = ["linkme"]

[dependencies]
extern-trait = "0.3"
kerrno.workspace = true
kaddr_layout.workspace = true
khal.workspace = true
kspin.workspace = true
ksync.workspace = true
kprocess.workspace = true
ktask.workspace = true
linkme.workspace = true
memaddr.workspace = true
memspace.workspace = true
osvm.workspace = true
unittest.workspace = true
unittest_support.workspace = true
