[package]
name = "timer-driver"
description = "platform clock source and clock event providers for X-Kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
default = []
arm-timer-resume-fixup = []
vmm = []

[dependencies]
khal = { workspace = true }
ktime_types = { workspace = true }
kirq = { workspace = true }
kbuild_config = { workspace = true }
kcpu_id_map = { workspace = true }
kiface = { workspace = true }
klazy = { workspace = true }
log = "0.4"
percpu.workspace = true
unittest.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu.workspace = true
of = { workspace = true }
int_ratio = { workspace = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
kernel_boot = { workspace = true }
int_ratio = { workspace = true }
raw-cpuid = "11.5"
x2apic = "0.5"
x86_64 = { workspace = true }
x86_apic = { workspace = true }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = "0.14"
sbi-rt = { version = "0.0.3", features = ["legacy"] }
